#+TITLE: Merging Graphical and Text-Based Editor
#+AUTHOR: RC Team
#+LATEX_CLASS: koma-article
#+OPTIONS: toc:nil 
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \onehalfspacing

** Introduction :luc:

- Only one editor
- Editors are no longer to be selected for the entire expositions but
per page. 
- Each page of an exposition 

- how to select editor per page?
- transform one into another?

- tools have index

- text-based as reader/mobile mode, 1d order, can be viewed in two ways

- text format for expositions (json)

  
** Changes to the text-based editor :casper:

Ideally the document is no longer one long markdown file, but a linear sequence of RC-tools.
The graphical exposition is a 2d positioned set of tools.

exposition =
    MetaData [ object1, object2, object3 ..  , objectN ] Style
  
objects:
   Text (markdown)
   HTML
   Media tool -> 
      Picture / Video / Audio /  Pdf / Media-set / Embed


??? -> A text can use media inline, by means of !{}  

** Media repo integration :casper:

Media tab should allow users to search and filter for media repo tags, keywords.

*** Media Tab > Fix icons for media upload and repo adding
    The button to add repositories (like Madek), should not be a "+", but a "add repo" text.
    The "+" should be reserved for uploading media files.

*** Media Repo View > Mode where media repo replaces the weave editor, so user can create sets manage tags etc..
    Have the repo appear in the graphical editor.... (hmm loading time??)

*** Technical > How could state be synced between media lists and repo's ? For example, when user is opening multiple tabs.
*** From set to exposition

** Changes and Adjustments :casper:
- Scrollbars on text tools. User defines width, height is defined by length of content (basically a CSS of "height:unset")
  This behavior should be default, but can be turned of in "options" menu.
- Layers
  * all objects have a layer number
  * only one layer can be edited at a time
  * you can turn the visibility of a layer on or off
- Edit tab, selecting a tool directly loads editor in sidebar.
- Keyboard cursors nudging tools.
- Form / block editor / media list would still be visible. drag and drop.
- Table of contents:
  - When a new page is created, the RC asks wether it should be added to the table of contents.
  - Pages that are not linked should have a different color.
- upload dialogues 
  When a tool is added, prompt user to upload a file directly.
- Different types of import (material to be turned into objects)
    

** Question :luc:
- One type for both kinds of pages? (Just different ways of displaying)
- How to send events to/from elm elements (text-based editor and media
  repo) to/from graphical editor and media list?
- Possible function mapping over expositions (filtering, adjustments, ordering etc.).
- Possible real-time exposition editing.
